/**
 * Blog posts migrated from the live Cadocary site.
 *
 * Only the two polished posts are migrated (the rough drafts and empty stubs
 * are intentionally skipped). Each post is represented as structured data with
 * a title, slug, and an ordered list of blocks. Blocks are a small superset of
 * the shared ContentBlock shapes plus a `link` block, so we can faithfully
 * preserve the xkcd image references and external links from the source
 * markdown.
 *
 * The blog is not part of the content-validation content model (products/
 * projects/slides/mission/ia); it is authored here as typed TypeScript so the
 * blog index and post pages share one source of truth and stay typechecked.
 */

export type BlogBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading"; level: 2 | 3; text: string }
  /** An external image reference (e.g. an xkcd comic), preserving its link. */
  | { type: "figure"; href: string; alt: string; caption?: string }
  /** A labeled external link (e.g. a calculator). */
  | { type: "link"; href: string; label: string };

export interface BlogPost {
  /** URL slug -> /blog/{slug}. */
  slug: string;
  /** IA page id for this post. */
  pageId: string;
  /** Post title. */
  title: string;
  /** Short summary for the blog index. */
  summary: string;
  /** The post body, in order. */
  blocks: BlogBlock[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "consulting-consultants",
    pageId: "blog-consulting-consultants",
    title: "Consulting the Consultants: project vs hourly billing incentives",
    summary:
      "The value of automation is a simple calculation — but how you bill it changes the incentives for both client and consultant.",
    blocks: [
      {
        type: "figure",
        href: "https://xkcd.com/1205/",
        alt: 'Return on Time: A new take on "Return on Investment"',
        caption: "xkcd 1205 — Is It Worth the Time?",
      },
      {
        type: "figure",
        href: "https://xkcd.com/974/",
        alt: "In how long of a run?",
        caption: "xkcd 974 — The General Problem",
      },
      {
        type: "figure",
        href: "https://xkcd.com/1319/",
        alt: "Difficulty of maintenance MUST be less than difficulty of task.",
        caption: "xkcd 1319 — Automation",
      },
      {
        type: "figure",
        href: "https://xkcd.com/951/",
        alt: "Outsourcing vs Automating",
        caption: "xkcd 951 — Working",
      },
      {
        type: "paragraph",
        text: "The value generated by any piece of automation is a relatively simple calculation:",
      },
      {
        type: "paragraph",
        text: "(human hours saved) × (hourly rate of human) = (value generated by software), a.k.a. (hrs) × ($/hr) = ($).",
      },
      {
        type: "paragraph",
        text: "That said, there can be much quibbling over the precise value of (human hours saved), and many clients are unsatisfied with paying software the same hourly rate as they would pay a human.",
      },
      {
        type: "paragraph",
        text: "In practice, projects can be billed in one of two ways: (1) an agreed-upon amount of $ for the creation of an agreed-upon specification, or (2) an agreed-upon rate of $/hr for time spent working in pursuit of an agreed-upon result.",
      },
      {
        type: "paragraph",
        text: "In case (1), the primary risk to the Client is that they overpay for a project that the Consultant can easily achieve. The primary risk to the Consultant is that they underestimate the difficulty of delivering the Client's specification.",
      },
      {
        type: "paragraph",
        text: "In case (2), the primary risk to the Client is that they accumulate sunk cost on a Consultant that is ultimately incapable of delivering the result. The primary risk to the Consultant is that they are unable to arbitrage their expertise. ($1 to hit it, $100 to know where.)",
      },
      {
        type: "paragraph",
        text: "Computer automation development is ultimately an arbitrage of time between a Software Engineer and some other white-collar worker. The hope is that (hrs × $/hr) for the Software Engineer is less than (hrs × $/hr) for the other worker — that the value generated by the software exceeds the cost of its development.",
      },
      {
        type: "paragraph",
        text: "The chart above is honestly a great rule of thumb, especially because it compares return on Time instead of return on $. For example, an 8–12% return on $ can be achieved by not purchasing any software and instead simply buying the S&P. It remains to be examined whether that produces a return on Time for the investor.",
      },
    ],
  },
  {
    slug: "is-it-worth-the-time",
    pageId: "blog-is-it-worth-the-time",
    title: "Is It Worth the Time?",
    summary:
      "The comics and calculators we reach for when deciding whether a task is worth automating.",
    blocks: [
      {
        type: "figure",
        href: "https://xkcd.com/1205/",
        alt: 'Return on Time: A new take on "Return on Investment"',
        caption: "xkcd 1205 — Is It Worth the Time?",
      },
      {
        type: "figure",
        href: "https://xkcd.com/974/",
        alt: "In how long of a run?",
        caption: "xkcd 974 — The General Problem",
      },
      {
        type: "figure",
        href: "https://xkcd.com/1319/",
        alt: "Difficulty of maintenance MUST be less than difficulty of task.",
        caption: "xkcd 1319 — Automation",
      },
      {
        type: "figure",
        href: "https://xkcd.com/951/",
        alt: "Outsourcing vs Automating",
        caption: "xkcd 951 — Working",
      },
      {
        type: "paragraph",
        text: "Two handy calculators for deciding whether a repetitive task is worth automating:",
      },
      {
        type: "link",
        href: "https://c.albert-thompson.com/xkcd/",
        label: "Time Saver Calculator",
      },
      {
        type: "link",
        href: "https://isitworththetime.com/",
        label: "Money Saver Calculator",
      },
    ],
  },
];

/** Look up a single post by slug. */
export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
